version: '3.8'

services:
  kong-database:
    image: postgres:13
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - kong-net
    ports:
      - "5432:5432"
    env_file:
      - ./.env
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "kong"]
      interval: 5s
      retries: 5
      timeout: 3s

  kong-setup:
    image: kong/kong-gateway:3.9.0.1
    environment:
      - KONG_DATABASE=${KONG_DATABASE}
      - KONG_PG_HOST=${KONG_PG_HOST}
      - KONG_PG_USER=${KONG_PG_USER}
      - KONG_PG_PASSWORD=${KONG_PG_PASSWORD}
      - KONG_PASSWORD=${KONG_PASSWORD}
      - KONG_DECLARATIVE_CONFIG=${KONG_DECLARATIVE_CONFIG}
    networks:
      - kong-net
    env_file:
      - ./.env
    command: ["/bin/sh", "-c", "kong migrations bootstrap && kong config db_import /kong/declarative/kong.yml"]
    depends_on:
      kong-database:
        condition: service_healthy
    volumes:
      - ./declarative:/kong/declarative/

  kong-gateway:
    image: kong/kong-gateway:3.9.0.1
    environment:
      - KONG_DATABASE=${KONG_DATABASE}
      - KONG_PG_HOST=${KONG_PG_HOST}
      - KONG_PG_USER=${KONG_PG_USER}
      - KONG_PG_PASSWORD=${KONG_PG_PASSWORD}
      - KONG_PROXY_ACCESS_LOG=${KONG_PROXY_ACCESS_LOG}
      - KONG_ADMIN_ACCESS_LOG=${KONG_ADMIN_ACCESS_LOG}
      - KONG_PROXY_ERROR_LOG=${KONG_PROXY_ERROR_LOG}
      - KONG_ADMIN_ERROR_LOG=${KONG_ADMIN_ERROR_LOG}
      - KONG_ADMIN_LISTEN=${KONG_ADMIN_LISTEN}
      - KONG_ADMIN_GUI_URL=${KONG_ADMIN_GUI_URL}
      - KONG_DECLARATIVE_CONFIG=${KONG_DECLARATIVE_CONFIG}
    networks:
      - kong-net
    env_file:
      - ./.env
    depends_on:
      kong-database:
        condition: service_healthy
      kong-setup:
        condition: service_completed_successfully
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "8444:8444"
      - "8002:8002"
      - "8445:8445"
      - "8003:8003"
      - "8004:8004"
    volumes:
      - ./declarative:/kong/declarative/


  nginx1:
    image: nginx:latest
    container_name: nginx1
    networks:
      - kong-net
    ports:
      - "8081:80"
    volumes:
      - ./nginx/nginx1:/usr/share/nginx/html

  nginx2:
    image: nginx:latest
    container_name: nginx2
    networks:
      - kong-net
    ports:
      - "8082:80"
    volumes:
      - ./nginx/nginx2:/usr/share/nginx/html

networks:
  kong-net:
